# -*- coding: utf-8 -*-
"""LAB 2 DAV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5QNC2pcQzmUJmCsvwnQrNuCohQ_VZQX
"""

import numpy as np
import pandas as pd

data = {
    "Name":["Rahul", "Priya", "Aisha", "Arjun", "Sneha","Vikram", "Neha", "Rohan",
          "Ananya", "Karan","Meera", "Aditya", "Pooja", "Ravi", "Kavya","Aman",
          "Isha", "Nikhil", "Simran", "Varun","Tanya", "Sahil", "Diya", "Manish",
          "Riya"],
    "Marks":[85, 92, np.nan,88, 95,67, 81, np.nan, 76, 90,
             84, 73, 89, np.nan, 91,65, 87, 79, 94, np.nan,
             72, 86, 68, 83, 97],
    "Age":  [20, 21, 19, np.nan, 20,23, 21, 19, 22, np.nan,20, 21, 19, 22, 20,
            23, np.nan, 21, 20, 22, np.nan, 23, 21, np.nan, 20],
    "City": ["Mysuru", "Bengaluru", "Hubballi", "Mangaluru", "Belagavi","Mysuru",
             "Dharwad", "Kalaburagi", "Ballari", "Shivamogga",
            "Bengaluru", "Tumakuru", "Mysuru", "Davanagere", "Udupi",
            "Mangaluru", "Hassan", "Vijayapura", "Bidar", "Mysuru",
            "Hubballi", "Hosapete", "Chikkamagaluru", "Raichur", "Bengaluru"]
}
df = pd.DataFrame(data)
print(df)

print("Shape of dataset (rows,columns):",df.shape)
print("\nColumn names:",df.columns.tolist())
print("\nData types of each column:",df.dtypes)

print("\n\nInformation : \n")
df.info()
print("\n\nDiscriptive Statistics (numerical columns):")
print(df.describe())
print("\nMean : \n",df.mean(numeric_only=True))
print("\nMedian :\n",df.median(numeric_only=True))
print("\nMode :\n",df.mode(numeric_only=True))
print("\nStandard Deviation:\n",df.std(numeric_only=True))

print("\n\nNull Entries : \n")
print(df.isnull())
print("\nTotal Number of Null Entries : \n")
print(df.isnull().sum())
print("\nTotal missing values in dataset :",df.isnull().sum().sum())

print("\nDuplicate rows in dataset:")
print(df[df.duplicated()])
print("\nTotal number of duplicate rows in dataset :",df.duplicated().sum())
print("\nEDA process complted successfully!")
